/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Templates;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import models.Emprendedor;
import models.Usuario;

/**
 *
 * @author samuelmendoza
 */
public class DashboardEmprendedor extends javax.swing.JFrame {

    /**
     * Creates new form DashboardEmprendedor
     */
    
    private Emprendedor emprendedor;    
    public DashboardEmprendedor(Usuario usuario) {
        initComponents();
        
        if (usuario instanceof Emprendedor) {
            this.emprendedor = (Emprendedor) usuario;
        }
        
        
        
        JOptionPane.showMessageDialog(null, "Acabas de iniciar sesion a nombre de: " + emprendedor.getName());
        
        PanelContenedor.setLayout(new BorderLayout());
        DashboardE De = new DashboardE(usuario);
        De.setSize(1549, 930);
        De.setLocation(0, 0);
        
        PanelContenedor.removeAll();
        PanelContenedor.add(De, BorderLayout.CENTER);
        PanelContenedor.revalidate();
        PanelContenedor.repaint();
        
        
        
    }
    
    private void resetButtons() {
    // Restaurar todos los botones al color original
    btnHome.setBackground(new Color(18, 65, 112));
    btnHome.setForeground(Color.white);
    
    btnPedidos.setBackground(new Color(18, 65, 112));
    btnPedidos.setForeground(Color.white);
    
    btnProductos.setBackground(new Color(18, 65, 112));
    btnProductos.setForeground(Color.white);
    
    btnFinanzas.setBackground(new Color(18, 65, 112));
    btnFinanzas.setForeground(Color.white);
    
    btnPerfil.setBackground(new Color(18, 65, 112));
    btnPerfil.setForeground(Color.white);
    
    btnMetricas.setBackground(new Color(18, 65, 112));
    btnMetricas.setForeground(Color.white);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        btnHome = new RoundersComponents.ButtonRound();
        btnPedidos = new RoundersComponents.ButtonRound();
        btnFinanzas = new RoundersComponents.ButtonRound();
        btnPerfil = new RoundersComponents.ButtonRound();
        buttonRound5 = new RoundersComponents.ButtonRound();
        btnProductos = new RoundersComponents.ButtonRound();
        btnMetricas = new RoundersComponents.ButtonRound();
        jLabel2 = new javax.swing.JLabel();
        PanelContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(18, 65, 112));
        jPanel1.setLayout(new java.awt.BorderLayout());

        menu.setBackground(new java.awt.Color(18, 65, 112));
        menu.setPreferredSize(new java.awt.Dimension(240, 930));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setBackground(new java.awt.Color(18, 65, 112));
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Home");
        btnHome.setFont(new java.awt.Font("Noto Sans Kannada", 1, 18)); // NOI18N
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnHome.setPreferredSize(new java.awt.Dimension(240, 23));
        btnHome.setRoundBottomLeft(30);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        menu.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 200, 40));

        btnPedidos.setBackground(new java.awt.Color(18, 65, 112));
        btnPedidos.setForeground(new java.awt.Color(255, 255, 255));
        btnPedidos.setText("Pedidos");
        btnPedidos.setFont(new java.awt.Font("Noto Sans Kannada", 1, 18)); // NOI18N
        btnPedidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPedidos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPedidos.setRoundBottomLeft(30);
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });
        menu.add(btnPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 200, 40));

        btnFinanzas.setBackground(new java.awt.Color(18, 65, 112));
        btnFinanzas.setForeground(new java.awt.Color(255, 255, 255));
        btnFinanzas.setText("Finanzas");
        btnFinanzas.setFont(new java.awt.Font("Noto Sans Kannada", 1, 18)); // NOI18N
        btnFinanzas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFinanzas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnFinanzas.setRoundBottomLeft(30);
        btnFinanzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinanzasActionPerformed(evt);
            }
        });
        menu.add(btnFinanzas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 200, 40));

        btnPerfil.setBackground(new java.awt.Color(18, 65, 112));
        btnPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnPerfil.setText("Perfil");
        btnPerfil.setFont(new java.awt.Font("Noto Sans Kannada", 1, 18)); // NOI18N
        btnPerfil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPerfil.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPerfil.setRoundBottomLeft(30);
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        menu.add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 200, 40));

        buttonRound5.setBackground(new java.awt.Color(18, 65, 112));
        buttonRound5.setForeground(new java.awt.Color(255, 255, 255));
        buttonRound5.setText("Cerrar Sesión");
        buttonRound5.setFont(new java.awt.Font("Noto Sans Kannada", 0, 18)); // NOI18N
        buttonRound5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonRound5.setVerifyInputWhenFocusTarget(false);
        buttonRound5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRound5ActionPerformed(evt);
            }
        });
        menu.add(buttonRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 870, 180, 40));

        btnProductos.setBackground(new java.awt.Color(18, 65, 112));
        btnProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnProductos.setText("Productos");
        btnProductos.setFont(new java.awt.Font("Noto Sans Kannada", 1, 18)); // NOI18N
        btnProductos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProductos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnProductos.setPreferredSize(new java.awt.Dimension(240, 23));
        btnProductos.setRoundBottomLeft(30);
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        menu.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 200, 40));

        btnMetricas.setBackground(new java.awt.Color(18, 65, 112));
        btnMetricas.setForeground(new java.awt.Color(255, 255, 255));
        btnMetricas.setText("Metricas");
        btnMetricas.setFont(new java.awt.Font("Noto Sans Kannada", 1, 18)); // NOI18N
        btnMetricas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMetricas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMetricas.setRoundBottomLeft(30);
        btnMetricas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetricasActionPerformed(evt);
            }
        });
        menu.add(btnMetricas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 200, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poo_wep_app/images/IconoFrameApp-small.png"))); // NOI18N
        menu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jPanel1.add(menu, java.awt.BorderLayout.LINE_START);

        PanelContenedor.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelContenedorLayout = new javax.swing.GroupLayout(PanelContenedor);
        PanelContenedor.setLayout(PanelContenedorLayout);
        PanelContenedorLayout.setHorizontalGroup(
            PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1549, Short.MAX_VALUE)
        );
        PanelContenedorLayout.setVerticalGroup(
            PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );

        jPanel1.add(PanelContenedor, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        // TODO add your handling code here:
        resetButtons();
        
        PedidosEmprendedor Pe = new PedidosEmprendedor();
        Pe.setSize(1549, 930);
        Pe.setLocation(0, 0);
        
        PanelContenedor.removeAll();
        PanelContenedor.add(Pe, BorderLayout.CENTER);
        PanelContenedor.revalidate();
        PanelContenedor.repaint();
        
        
        btnPedidos.setBackground(Color.white);
        btnPedidos.setForeground(Color.black);
        
            
        
    }//GEN-LAST:event_btnPedidosActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        resetButtons();
        
        DashboardE De = new DashboardE(emprendedor);
        De.setSize(1549, 930);
        De.setLocation(0, 0);
        
        PanelContenedor.removeAll();
        PanelContenedor.add(De, BorderLayout.CENTER);
        PanelContenedor.revalidate();
        PanelContenedor.repaint();
        
        btnHome.setBackground(Color.white);
        btnHome.setForeground(Color.black);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:
        resetButtons();
        
        ProductosEmprendedor ProE = new ProductosEmprendedor(emprendedor);
        ProE.setSize(1549, 930);
        ProE.setLocation(0, 0);
        
        PanelContenedor.removeAll();
        PanelContenedor.add(ProE, BorderLayout.CENTER);
        PanelContenedor.revalidate();
        PanelContenedor.repaint();
        
        btnProductos.setBackground(Color.white);
        btnProductos.setForeground(Color.black);
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnFinanzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinanzasActionPerformed
        // TODO add your handling code here:
        resetButtons();
        
        Finanzas Fi = new Finanzas(emprendedor);
        Fi.setSize(1549, 930);
        Fi.setLocation(0, 0);
        
        PanelContenedor.removeAll();
        PanelContenedor.add(Fi, BorderLayout.CENTER);
        PanelContenedor.revalidate();
        PanelContenedor.repaint();
        
        
        
        btnFinanzas.setBackground(Color.white);
        btnFinanzas.setForeground(Color.black);
        
        
        
        
        
       
    }//GEN-LAST:event_btnFinanzasActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        // TODO add your handling code here:
        resetButtons();
        
        Perfil P = new Perfil(emprendedor);
        P.setSize(1549, 930);
        P.setLocation(0, 0);
        
        PanelContenedor.removeAll();
        PanelContenedor.add(P, BorderLayout.CENTER);
        PanelContenedor.revalidate();
        PanelContenedor.repaint();
        
        
        btnPerfil.setBackground(Color.white);
        btnPerfil.setForeground(Color.black);
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnMetricasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetricasActionPerformed
        // TODO add your handling code here:
        
        btnMetricas.setBackground(Color.white);
        btnMetricas.setForeground(Color.black);
        
    }//GEN-LAST:event_btnMetricasActionPerformed

    private void buttonRound5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRound5ActionPerformed
        // TODO add your handling code here:
        
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonRound5ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DashboardEmprendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DashboardEmprendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DashboardEmprendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DashboardEmprendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DashboardEmprendedor().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContenedor;
    private RoundersComponents.ButtonRound btnFinanzas;
    private RoundersComponents.ButtonRound btnHome;
    private RoundersComponents.ButtonRound btnMetricas;
    private RoundersComponents.ButtonRound btnPedidos;
    private RoundersComponents.ButtonRound btnPerfil;
    private RoundersComponents.ButtonRound btnProductos;
    private RoundersComponents.ButtonRound buttonRound5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
