/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Templates;

import java.awt.BorderLayout;

/**
 *
 * @author samuelmendoza
 */
public class DashboardEmprendedor extends javax.swing.JFrame {

    /**
     * Creates new form DashboardEmprendedor
     */
    public DashboardEmprendedor() {
        initComponents();
        
        PanelContenedor.setLayout(new BorderLayout());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        buttonRound1 = new RoundersComponents.ButtonRound();
        buttonRound2 = new RoundersComponents.ButtonRound();
        buttonRound3 = new RoundersComponents.ButtonRound();
        buttonRound4 = new RoundersComponents.ButtonRound();
        buttonRound5 = new RoundersComponents.ButtonRound();
        buttonRound6 = new RoundersComponents.ButtonRound();
        buttonRound7 = new RoundersComponents.ButtonRound();
        PanelContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(18, 65, 112));
        jPanel1.setLayout(new java.awt.BorderLayout());

        menu.setBackground(new java.awt.Color(18, 65, 112));
        menu.setPreferredSize(new java.awt.Dimension(240, 930));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonRound1.setBackground(new java.awt.Color(18, 65, 112));
        buttonRound1.setForeground(new java.awt.Color(255, 255, 255));
        buttonRound1.setText("Dashboard");
        buttonRound1.setFont(new java.awt.Font("Noto Sans Kannada", 1, 18)); // NOI18N
        buttonRound1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonRound1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonRound1.setPreferredSize(new java.awt.Dimension(240, 23));
        buttonRound1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRound1ActionPerformed(evt);
            }
        });
        menu.add(buttonRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 180, 40));

        buttonRound2.setBackground(new java.awt.Color(18, 65, 112));
        buttonRound2.setForeground(new java.awt.Color(255, 255, 255));
        buttonRound2.setText("Pedidos");
        buttonRound2.setFont(new java.awt.Font("Noto Sans Kannada", 1, 18)); // NOI18N
        buttonRound2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonRound2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonRound2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRound2ActionPerformed(evt);
            }
        });
        menu.add(buttonRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 180, 40));

        buttonRound3.setBackground(new java.awt.Color(18, 65, 112));
        buttonRound3.setForeground(new java.awt.Color(255, 255, 255));
        buttonRound3.setText("Finanzas");
        buttonRound3.setFont(new java.awt.Font("Noto Sans Kannada", 1, 18)); // NOI18N
        buttonRound3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonRound3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menu.add(buttonRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 180, 40));

        buttonRound4.setBackground(new java.awt.Color(18, 65, 112));
        buttonRound4.setForeground(new java.awt.Color(255, 255, 255));
        buttonRound4.setText("Perfil");
        buttonRound4.setFont(new java.awt.Font("Noto Sans Kannada", 1, 18)); // NOI18N
        buttonRound4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonRound4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menu.add(buttonRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 180, 40));

        buttonRound5.setBackground(new java.awt.Color(18, 65, 112));
        buttonRound5.setForeground(new java.awt.Color(255, 255, 255));
        buttonRound5.setText("Cerrar Sesión");
        buttonRound5.setFont(new java.awt.Font("Noto Sans Kannada", 0, 18)); // NOI18N
        buttonRound5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonRound5.setVerifyInputWhenFocusTarget(false);
        menu.add(buttonRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 870, 180, 40));

        buttonRound6.setBackground(new java.awt.Color(18, 65, 112));
        buttonRound6.setForeground(new java.awt.Color(255, 255, 255));
        buttonRound6.setText("Productos");
        buttonRound6.setFont(new java.awt.Font("Noto Sans Kannada", 1, 18)); // NOI18N
        buttonRound6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonRound6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonRound6.setPreferredSize(new java.awt.Dimension(240, 23));
        buttonRound6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRound6ActionPerformed(evt);
            }
        });
        menu.add(buttonRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 180, 40));

        buttonRound7.setBackground(new java.awt.Color(18, 65, 112));
        buttonRound7.setForeground(new java.awt.Color(255, 255, 255));
        buttonRound7.setText("Metricas");
        buttonRound7.setFont(new java.awt.Font("Noto Sans Kannada", 1, 18)); // NOI18N
        buttonRound7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonRound7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menu.add(buttonRound7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 180, 40));

        jPanel1.add(menu, java.awt.BorderLayout.LINE_START);

        PanelContenedor.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelContenedorLayout = new javax.swing.GroupLayout(PanelContenedor);
        PanelContenedor.setLayout(PanelContenedorLayout);
        PanelContenedorLayout.setHorizontalGroup(
            PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1549, Short.MAX_VALUE)
        );
        PanelContenedorLayout.setVerticalGroup(
            PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );

        jPanel1.add(PanelContenedor, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRound2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRound2ActionPerformed
        // TODO add your handling code here:
        PedidosEmprendedor Pe = new PedidosEmprendedor();
        Pe.setSize(1549, 930);
        Pe.setLocation(0, 0);
        
        PanelContenedor.removeAll();
        PanelContenedor.add(Pe, BorderLayout.CENTER);
        PanelContenedor.revalidate();
        PanelContenedor.repaint();
    }//GEN-LAST:event_buttonRound2ActionPerformed

    private void buttonRound1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRound1ActionPerformed
        // TODO add your handling code here:
        ProductosEmprendedor ProE = new ProductosEmprendedor();
        ProE.setSize(1549, 930);
        ProE.setLocation(0, 0);
        
        PanelContenedor.removeAll();
        PanelContenedor.add(ProE, BorderLayout.CENTER);
        PanelContenedor.revalidate();
        PanelContenedor.repaint();
    }//GEN-LAST:event_buttonRound1ActionPerformed

    private void buttonRound6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRound6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRound6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardEmprendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardEmprendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardEmprendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardEmprendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardEmprendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContenedor;
    private RoundersComponents.ButtonRound buttonRound1;
    private RoundersComponents.ButtonRound buttonRound2;
    private RoundersComponents.ButtonRound buttonRound3;
    private RoundersComponents.ButtonRound buttonRound4;
    private RoundersComponents.ButtonRound buttonRound5;
    private RoundersComponents.ButtonRound buttonRound6;
    private RoundersComponents.ButtonRound buttonRound7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
