/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Templates;
import java.text.NumberFormat;
import java.util.Locale;
import models.Emprendedor;
import models.Emprendedor;
import models.Usuario;


/**
 *
 * @author samuelmendoza
 */
public class Finanzas extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    private Emprendedor emprendedor;
    public Finanzas(Usuario u) {
        initComponents();
        
        
        if (u instanceof Emprendedor) {
            this.emprendedor = (Emprendedor) u;
        }
        
        double totalIngresos = emprendedor.getTotalIngresos();
        double totalEgresos = emprendedor.getTotalEgresos();
        
        NumberFormat formatoCOP = NumberFormat.getCurrencyInstance(new Locale("es", "CO"));
        lblTotalIngresos.setText(formatoCOP.format(totalIngresos));
        lblTotalEgresos.setText(formatoCOP.format(totalEgresos));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        panelRound1 = new RoundersComponents.PanelRound();
        panelRound3 = new RoundersComponents.PanelRound();
        panelRound4 = new RoundersComponents.PanelRound();
        panelRound5 = new RoundersComponents.PanelRound();
        panelRound6 = new RoundersComponents.PanelRound();
        panelRound7 = new RoundersComponents.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        panelRound13 = new RoundersComponents.PanelRound();
        jLabel11 = new javax.swing.JLabel();
        lblTotalIngresos = new javax.swing.JLabel();
        RegistrarIngreso = new RoundersComponents.ButtonRound();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        panelRound2 = new RoundersComponents.PanelRound();
        panelRound8 = new RoundersComponents.PanelRound();
        panelRound9 = new RoundersComponents.PanelRound();
        panelRound10 = new RoundersComponents.PanelRound();
        panelRound11 = new RoundersComponents.PanelRound();
        panelRound12 = new RoundersComponents.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        panelRound14 = new RoundersComponents.PanelRound();
        jLabel12 = new javax.swing.JLabel();
        lblTotalEgresos = new javax.swing.JLabel();
        RegistrarEgreso = new RoundersComponents.ButtonRound();

        jPanel1.setPreferredSize(new java.awt.Dimension(1549, 930));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1549, 10));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1549, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(20, 920));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(20, 920));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(1549, 10));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1549, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.BorderLayout());

        panelRound1.setBackground(new java.awt.Color(18, 65, 112));
        panelRound1.setPreferredSize(new java.awt.Dimension(759, 910));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);
        panelRound1.setLayout(new java.awt.BorderLayout());

        panelRound3.setBackground(new java.awt.Color(18, 65, 112));
        panelRound3.setRoundBottomLeft(50);
        panelRound3.setRoundBottomRight(50);
        panelRound3.setRoundTopLeft(50);
        panelRound3.setRoundTopRight(40);

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 759, Short.MAX_VALUE)
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelRound1.add(panelRound3, java.awt.BorderLayout.PAGE_START);

        panelRound4.setBackground(new java.awt.Color(18, 65, 112));
        panelRound4.setRoundBottomLeft(50);
        panelRound4.setRoundBottomRight(50);
        panelRound4.setRoundTopLeft(50);
        panelRound4.setRoundTopRight(40);

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );

        panelRound1.add(panelRound4, java.awt.BorderLayout.LINE_START);

        panelRound5.setBackground(new java.awt.Color(18, 65, 112));
        panelRound5.setRoundBottomLeft(50);
        panelRound5.setRoundBottomRight(50);
        panelRound5.setRoundTopLeft(50);
        panelRound5.setRoundTopRight(40);

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );

        panelRound1.add(panelRound5, java.awt.BorderLayout.LINE_END);

        panelRound6.setBackground(new java.awt.Color(18, 65, 112));
        panelRound6.setRoundBottomLeft(50);
        panelRound6.setRoundBottomRight(50);
        panelRound6.setRoundTopLeft(50);
        panelRound6.setRoundTopRight(40);

        javax.swing.GroupLayout panelRound6Layout = new javax.swing.GroupLayout(panelRound6);
        panelRound6.setLayout(panelRound6Layout);
        panelRound6Layout.setHorizontalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 759, Short.MAX_VALUE)
        );
        panelRound6Layout.setVerticalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelRound1.add(panelRound6, java.awt.BorderLayout.PAGE_END);

        panelRound7.setBackground(new java.awt.Color(221, 244, 231));
        panelRound7.setRoundBottomLeft(50);
        panelRound7.setRoundBottomRight(50);
        panelRound7.setRoundTopLeft(50);
        panelRound7.setRoundTopRight(50);
        panelRound7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Noto Sans Kannada", 1, 36)); // NOI18N
        jLabel2.setText("INGRESOS");
        panelRound7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));
        panelRound7.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 510, 20));

        jLabel3.setFont(new java.awt.Font("Noto Sans Kannada", 0, 18)); // NOI18N
        jLabel3.setText("Metodo de Pago:");
        panelRound7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel4.setFont(new java.awt.Font("Noto Sans Kannada", 0, 18)); // NOI18N
        jLabel4.setText("Monto del ingreso: ");
        panelRound7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Noto Sans Kannada", 0, 18)); // NOI18N
        jLabel5.setText("Fecha:");
        panelRound7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Noto Sans Kannada", 0, 18)); // NOI18N
        jLabel6.setText("Descripción:");
        panelRound7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));
        panelRound7.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 310, -1));
        panelRound7.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 310, -1));
        panelRound7.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 310, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Transferencia", " " }));
        panelRound7.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 310, -1));

        panelRound13.setBackground(new java.awt.Color(255, 255, 255));
        panelRound13.setRoundBottomLeft(50);
        panelRound13.setRoundBottomRight(50);
        panelRound13.setRoundTopLeft(50);
        panelRound13.setRoundTopRight(50);
        panelRound13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("Total Ingresos");
        panelRound13.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 19, -1, -1));

        lblTotalIngresos.setFont(new java.awt.Font("Noto Sans Kannada", 1, 24)); // NOI18N
        lblTotalIngresos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelRound13.add(lblTotalIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 310, 100));

        panelRound7.add(panelRound13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 490, 160));

        RegistrarIngreso.setBackground(new java.awt.Color(38, 102, 127));
        RegistrarIngreso.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarIngreso.setText("REGISTRAR");
        RegistrarIngreso.setRoundBottomLeft(30);
        panelRound7.add(RegistrarIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 210, 35));

        panelRound1.add(panelRound7, java.awt.BorderLayout.CENTER);

        jPanel6.add(panelRound1, java.awt.BorderLayout.LINE_START);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(10, 910));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel8, java.awt.BorderLayout.LINE_START);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.BorderLayout());

        panelRound2.setBackground(new java.awt.Color(18, 65, 112));
        panelRound2.setRoundBottomLeft(50);
        panelRound2.setRoundBottomRight(50);
        panelRound2.setRoundTopLeft(50);
        panelRound2.setRoundTopRight(50);
        panelRound2.setLayout(new java.awt.BorderLayout());

        panelRound8.setBackground(new java.awt.Color(18, 65, 112));
        panelRound8.setRoundBottomLeft(50);
        panelRound8.setRoundBottomRight(50);
        panelRound8.setRoundTopLeft(50);
        panelRound8.setRoundTopRight(50);

        javax.swing.GroupLayout panelRound8Layout = new javax.swing.GroupLayout(panelRound8);
        panelRound8.setLayout(panelRound8Layout);
        panelRound8Layout.setHorizontalGroup(
            panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        panelRound8Layout.setVerticalGroup(
            panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelRound2.add(panelRound8, java.awt.BorderLayout.PAGE_START);

        panelRound9.setBackground(new java.awt.Color(18, 65, 112));
        panelRound9.setRoundBottomLeft(50);
        panelRound9.setRoundBottomRight(50);
        panelRound9.setRoundTopLeft(50);
        panelRound9.setRoundTopRight(50);

        javax.swing.GroupLayout panelRound9Layout = new javax.swing.GroupLayout(panelRound9);
        panelRound9.setLayout(panelRound9Layout);
        panelRound9Layout.setHorizontalGroup(
            panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelRound9Layout.setVerticalGroup(
            panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );

        panelRound2.add(panelRound9, java.awt.BorderLayout.LINE_START);

        panelRound10.setBackground(new java.awt.Color(18, 65, 112));
        panelRound10.setRoundBottomLeft(50);
        panelRound10.setRoundBottomRight(50);
        panelRound10.setRoundTopLeft(50);
        panelRound10.setRoundTopRight(50);

        javax.swing.GroupLayout panelRound10Layout = new javax.swing.GroupLayout(panelRound10);
        panelRound10.setLayout(panelRound10Layout);
        panelRound10Layout.setHorizontalGroup(
            panelRound10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelRound10Layout.setVerticalGroup(
            panelRound10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );

        panelRound2.add(panelRound10, java.awt.BorderLayout.LINE_END);

        panelRound11.setBackground(new java.awt.Color(18, 65, 112));
        panelRound11.setRoundBottomLeft(50);
        panelRound11.setRoundBottomRight(50);
        panelRound11.setRoundTopLeft(50);
        panelRound11.setRoundTopRight(50);

        javax.swing.GroupLayout panelRound11Layout = new javax.swing.GroupLayout(panelRound11);
        panelRound11.setLayout(panelRound11Layout);
        panelRound11Layout.setHorizontalGroup(
            panelRound11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        panelRound11Layout.setVerticalGroup(
            panelRound11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelRound2.add(panelRound11, java.awt.BorderLayout.PAGE_END);

        panelRound12.setBackground(new java.awt.Color(221, 244, 231));
        panelRound12.setRoundBottomLeft(50);
        panelRound12.setRoundBottomRight(50);
        panelRound12.setRoundTopLeft(50);
        panelRound12.setRoundTopRight(50);
        panelRound12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Noto Sans Kannada", 1, 36)); // NOI18N
        jLabel1.setText("EGRESOS");
        panelRound12.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));
        panelRound12.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 500, 20));

        jLabel7.setFont(new java.awt.Font("Noto Sans Kannada", 0, 18)); // NOI18N
        jLabel7.setText("Monto del egreso: ");
        panelRound12.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Noto Sans Kannada", 0, 18)); // NOI18N
        jLabel8.setText("Fecha:");
        panelRound12.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Transferencia", " " }));
        panelRound12.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 310, -1));
        panelRound12.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 310, -1));

        jLabel9.setFont(new java.awt.Font("Noto Sans Kannada", 0, 18)); // NOI18N
        jLabel9.setText("Descripción:");
        panelRound12.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));
        panelRound12.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 310, -1));

        jLabel10.setFont(new java.awt.Font("Noto Sans Kannada", 0, 18)); // NOI18N
        jLabel10.setText("Metodo de Pago:");
        panelRound12.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));
        panelRound12.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 310, -1));

        panelRound14.setBackground(new java.awt.Color(255, 255, 255));
        panelRound14.setRoundBottomLeft(50);
        panelRound14.setRoundBottomRight(50);
        panelRound14.setRoundTopLeft(50);
        panelRound14.setRoundTopRight(50);
        panelRound14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Total de egresos");
        panelRound14.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblTotalEgresos.setFont(new java.awt.Font("Noto Sans Kannada", 1, 24)); // NOI18N
        lblTotalEgresos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelRound14.add(lblTotalEgresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 47, 310, 100));

        panelRound12.add(panelRound14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 490, 160));

        RegistrarEgreso.setBackground(new java.awt.Color(38, 102, 127));
        RegistrarEgreso.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarEgreso.setText("REGISTRAR");
        RegistrarEgreso.setRoundBottomLeft(30);
        panelRound12.add(RegistrarEgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 210, 35));

        panelRound2.add(panelRound12, java.awt.BorderLayout.CENTER);

        jPanel9.add(panelRound2, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RoundersComponents.ButtonRound RegistrarEgreso;
    private RoundersComponents.ButtonRound RegistrarIngreso;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblTotalEgresos;
    private javax.swing.JLabel lblTotalIngresos;
    private RoundersComponents.PanelRound panelRound1;
    private RoundersComponents.PanelRound panelRound10;
    private RoundersComponents.PanelRound panelRound11;
    private RoundersComponents.PanelRound panelRound12;
    private RoundersComponents.PanelRound panelRound13;
    private RoundersComponents.PanelRound panelRound14;
    private RoundersComponents.PanelRound panelRound2;
    private RoundersComponents.PanelRound panelRound3;
    private RoundersComponents.PanelRound panelRound4;
    private RoundersComponents.PanelRound panelRound5;
    private RoundersComponents.PanelRound panelRound6;
    private RoundersComponents.PanelRound panelRound7;
    private RoundersComponents.PanelRound panelRound8;
    private RoundersComponents.PanelRound panelRound9;
    // End of variables declaration//GEN-END:variables
}
