/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Templates;
import java.awt.Window;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import models.Emprendedor;
import models.Usuario;

/**
 *
 * @author samuelmendoza
 */
public class Perfil extends javax.swing.JPanel {

    /**
     * Creates new form Perfil
     */
    private Emprendedor emprendedor;
    public Perfil(Usuario usuario) {
        initComponents();
        NombrePerfil.setEditable(false);
        
        if(usuario instanceof Emprendedor){
            this.emprendedor = (Emprendedor) usuario;
        }
        
        DeshabilitarCampos();
        
        NombrePerfil.setText(emprendedor.getName());
        ApellidoPerfil.setText(emprendedor.getLast_name());
        CorreoPerfil.setText(emprendedor.getEmail());
        TipoNegocioP.setText(emprendedor.getTipoNegocio());
        NombreNegocioP.setText(emprendedor.getNombreNegocio());
        CarreraPerfil.setText(emprendedor.getCarrera());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelRound1 = new RoundersComponents.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        TipoNegocioP = new javax.swing.JTextField();
        NombrePerfil = new javax.swing.JTextField();
        ApellidoPerfil = new javax.swing.JTextField();
        CorreoPerfil = new javax.swing.JTextField();
        NombreNegocioP = new javax.swing.JTextField();
        CarreraPerfil = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        buttonRound1 = new RoundersComponents.ButtonRound();
        EditarInfo = new RoundersComponents.ButtonRound();
        buttonRound3 = new RoundersComponents.ButtonRound();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1549, 930));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1549, 930));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(221, 244, 231));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Noto Sans Kannada", 1, 48)); // NOI18N
        jLabel1.setText("DATOS DE USUARIO");
        panelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));
        panelRound1.add(TipoNegocioP, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 230, 50));
        panelRound1.add(NombrePerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 230, 50));
        panelRound1.add(ApellidoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 230, 50));
        panelRound1.add(CorreoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 230, 50));
        panelRound1.add(NombreNegocioP, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 230, 50));
        panelRound1.add(CarreraPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 230, 50));

        jLabel2.setFont(new java.awt.Font("Noto Sans Kannada", 1, 14)); // NOI18N
        jLabel2.setText("TIPO DE NEGOCIO");
        panelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, -1, -1));

        jLabel3.setFont(new java.awt.Font("Noto Sans Kannada", 1, 14)); // NOI18N
        jLabel3.setText("NOMBRE");
        panelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Noto Sans Kannada", 1, 14)); // NOI18N
        jLabel4.setText("APELLIDO");
        panelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Noto Sans Kannada", 1, 14)); // NOI18N
        jLabel5.setText("CORREO");
        panelRound1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("Noto Sans Kannada", 1, 14)); // NOI18N
        jLabel6.setText("NOMBRE NEGOCIO");
        panelRound1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Noto Sans Kannada", 1, 14)); // NOI18N
        jLabel7.setText("CARRERA");
        panelRound1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, -1, -1));

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 140, 780, 650));

        buttonRound1.setBackground(new java.awt.Color(221, 244, 231));
        buttonRound1.setText("ELIMINAR CUENTA");
        buttonRound1.setRoundBottomLeft(30);
        buttonRound1.setRoundBottomRight(30);
        buttonRound1.setRoundTopLeft(30);
        buttonRound1.setRoundTopRight(30);
        buttonRound1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRound1ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 810, 250, 50));

        EditarInfo.setBackground(new java.awt.Color(221, 244, 231));
        EditarInfo.setText("EDITAR INFORMACIÓN");
        EditarInfo.setRoundBottomLeft(30);
        EditarInfo.setRoundBottomRight(30);
        EditarInfo.setRoundTopLeft(30);
        EditarInfo.setRoundTopRight(30);
        EditarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarInfoActionPerformed(evt);
            }
        });
        jPanel1.add(EditarInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 810, 250, 50));

        buttonRound3.setBackground(new java.awt.Color(221, 244, 231));
        buttonRound3.setText("GUARDAR");
        buttonRound3.setRoundBottomLeft(30);
        buttonRound3.setRoundBottomRight(30);
        buttonRound3.setRoundTopLeft(30);
        buttonRound3.setRoundTopRight(30);
        buttonRound3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRound3ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 810, 250, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EditarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarInfoActionPerformed
        // TODO add your handling code here:
        HabilitarCampos();
        String nombren = NombrePerfil.getText();
        String apellidon = ApellidoPerfil.getText();
        String TipoN = TipoNegocioP.getText();
        String nombreneg = NombreNegocioP.getText();
        String carrera = CarreraPerfil.getText();
        
        
        
        
    }//GEN-LAST:event_EditarInfoActionPerformed

    private void buttonRound3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRound3ActionPerformed
        // TODO add your handling code here:
        String nombren = NombrePerfil.getText();
        String apellidon = ApellidoPerfil.getText();
        String TipoN = TipoNegocioP.getText();
        String nombreneg = NombreNegocioP.getText();
        String carrera = CarreraPerfil.getText();
        
        emprendedor.setName(nombren);
        emprendedor.setLast_name(apellidon);
        emprendedor.setTipoNegocio(TipoN);
        emprendedor.setNombreNegocio(nombreneg);
        emprendedor.setCarrera(carrera);
        
        JOptionPane.showMessageDialog(null, "Datos de perfil actualizados");
        
        JOptionPane.showMessageDialog(null, "Nuevos datos: " + emprendedor.toString());
    }//GEN-LAST:event_buttonRound3ActionPerformed

    private void buttonRound1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRound1ActionPerformed
        // TODO add your handling code here:
        
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro de que deseas continuar?",
            "Advertencia",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        if (opcion == JOptionPane.YES_OPTION) {
            
            models.Main.GetListaUsuarios().Eliminar(emprendedor);
            JOptionPane.showMessageDialog(this, "Cuenta Eliminada");
            
            Window parentWindow = SwingUtilities.getWindowAncestor(this);
            parentWindow.dispose();
            
            new Login().setVisible(true);
            
        } else {
            JOptionPane.showMessageDialog(this, "Confirmamos que quieres seguir usando esta cuenta");
        }

    }//GEN-LAST:event_buttonRound1ActionPerformed

    
    public void DeshabilitarCampos(){
        NombrePerfil.setEnabled(false);
        ApellidoPerfil.setEnabled(false);
        CorreoPerfil.setEnabled(false);
        TipoNegocioP.setEnabled(false);
        NombreNegocioP.setEnabled(false);
        CarreraPerfil.setEnabled(false);
    }
    
    public void HabilitarCampos(){
        NombrePerfil.setEnabled(true);
        ApellidoPerfil.setEnabled(true);
        CorreoPerfil.setEnabled(false);
        TipoNegocioP.setEnabled(true);
        NombreNegocioP.setEnabled(true);
        CarreraPerfil.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoPerfil;
    private javax.swing.JTextField CarreraPerfil;
    private javax.swing.JTextField CorreoPerfil;
    private RoundersComponents.ButtonRound EditarInfo;
    private javax.swing.JTextField NombreNegocioP;
    private javax.swing.JTextField NombrePerfil;
    private javax.swing.JTextField TipoNegocioP;
    private RoundersComponents.ButtonRound buttonRound1;
    private RoundersComponents.ButtonRound buttonRound3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private RoundersComponents.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables
}
