/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Templates;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Emprendedor;
import models.Usuario;
import models.Producto;
import Estructuras.Nodo;
import java.text.NumberFormat;
import java.util.Locale;


/**
 *
 * @author samuelmendoza
 */
public class ProductosEmprendedor extends javax.swing.JPanel {

    /**
     * Creates new form ProductosEmprendedor
     */
    private Emprendedor emprendedor;
    public ProductosEmprendedor(Usuario u) {
        initComponents();
        
        if(u instanceof Emprendedor){
            this.emprendedor = (Emprendedor) u;
            cargarCategoriasSegunTipo();  // Cargar categorías al inicializar
        }
        

    }
    
    public void cargarCategoriasSegunTipo(){
         String TipoN = emprendedor.getTipoNegocio();
        
        jcCategoria.removeAllItems();
       
        switch(TipoN){
            case "Moda y Belleza":
            jcCategoria.addItem("Camisetas");
            jcCategoria.addItem("Hoodies");
            jcCategoria.addItem("Accesorios");
            jcCategoria.addItem("Bisutería");
            jcCategoria.addItem("Calzado");
            break;
            
        case "Gastronomía":
            jcCategoria.addItem("Postres");
            jcCategoria.addItem("Snacks");
            jcCategoria.addItem("Comidas rápidas");
            jcCategoria.addItem("Bebidas naturales");
            jcCategoria.addItem("Café");
            break;
            
        case "Tecnología":
            jcCategoria.addItem("Accesorios para celular");
            jcCategoria.addItem("Gadgets");
            jcCategoria.addItem("Reparaciones");
            jcCategoria.addItem("Software");
            break;
            
        case "Arte y Diseño":
            jcCategoria.addItem("Cuadernos personalizados");
            jcCategoria.addItem("Stickers");
            jcCategoria.addItem("Ilustraciones");
            jcCategoria.addItem("Arte digital");
            break;
            
        case "Educación":
            jcCategoria.addItem("Clases particulares");
            jcCategoria.addItem("Asesorías");
            jcCategoria.addItem("Resúmenes");
            jcCategoria.addItem("Trabajos académicos");
            break;
            
        case "Servicios Profesionales":
            jcCategoria.addItem("Fotografía");
            jcCategoria.addItem("Diseño gráfico");
            jcCategoria.addItem("Edición de video");
            jcCategoria.addItem("Ilustración");
            break;
            
        case "Salud y Bienestar":
            jcCategoria.addItem("Suplementos");
            jcCategoria.addItem("Productos naturales");
            jcCategoria.addItem("Sesiones de entrenamiento");
            break;
            
        case "Entretenimiento":
            jcCategoria.addItem("Eventos");
            jcCategoria.addItem("Música");
            jcCategoria.addItem("Shows");
            jcCategoria.addItem("Contenido digital");
            jcCategoria.addItem("Streaming");
            break;
            
        case "Sostenible / Ecológico":
            jcCategoria.addItem("Productos reciclados");
            jcCategoria.addItem("Artesanías ecológicas");
            jcCategoria.addItem("Ropa sostenible");
            break;
            
        case "Otro":
            jcCategoria.addItem("Otros productos");
            break;
        }
    }
    
    private void cargarTablaProductos() {
    // Obtener el modelo de la tabla
    DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
    
    // Limpiar la tabla antes de llenarla
    modelo.setRowCount(0);
    
    // Recorrer la lista de productos del emprendedor
    Nodo aux = emprendedor.getProductos().getPrimero();
    while (aux != null) {
        Producto p = (Producto) aux.getDato();
        
        NumberFormat formatoCOP = NumberFormat.getCurrencyInstance(new Locale("es", "CO"));
        String precioFormateado = formatoCOP.format(p.getPrecio());

        
        // Agregar fila con los datos del producto
        modelo.addRow(new Object[] {
            p.getCodigo(),
            p.getNombre(),
            precioFormateado,
            p.getStock(),
            p.getCategoria(),
            p.getEstado(),
            p.getDescripcion()
            
        });
        
        aux = aux.getEnlace();
    }
}

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        panelRound1 = new RoundersComponents.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        panelRound2 = new RoundersComponents.PanelRound();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jtfNombreProducto = new javax.swing.JTextField();
        jtfPrecioProducto = new javax.swing.JTextField();
        jtfStock = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        JtaDescripcionProducto = new javax.swing.JTextArea();
        btnRegitarProducto = new RoundersComponents.ButtonRound();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jcEstadoProducto = new javax.swing.JComboBox<>();
        jcCategoria = new javax.swing.JComboBox<>();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        panelRound3 = new RoundersComponents.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        buttonRound2 = new RoundersComponents.ButtonRound();
        buttonRound3 = new RoundersComponents.ButtonRound();
        buttonRound4 = new RoundersComponents.ButtonRound();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1549, 930));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(221, 244, 231));
        jPanel1.setPreferredSize(new java.awt.Dimension(1543, 10));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1543, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(221, 244, 231));
        jPanel2.setPreferredSize(new java.awt.Dimension(10, 944));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 934, Short.MAX_VALUE)
        );

        add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(221, 244, 231));
        jPanel3.setPreferredSize(new java.awt.Dimension(10, 944));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 934, Short.MAX_VALUE)
        );

        add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel4.setBackground(new java.awt.Color(221, 244, 231));
        jPanel4.setPreferredSize(new java.awt.Dimension(1543, 10));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1543, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel5.setLayout(new java.awt.BorderLayout());

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setPreferredSize(new java.awt.Dimension(1523, 150));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Noto Sans Kannada", 1, 36)); // NOI18N
        jLabel1.setText("Tus Productos");
        panelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jPanel5.add(panelRound1, java.awt.BorderLayout.PAGE_START);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(221, 244, 231));
        jPanel7.setPreferredSize(new java.awt.Dimension(1523, 10));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1523, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(221, 244, 231));
        jPanel9.setPreferredSize(new java.awt.Dimension(750, 774));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre ", "Precio", "Stock", "Categoría", "Estado", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel9.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel9, java.awt.BorderLayout.LINE_START);

        jPanel10.setLayout(new java.awt.BorderLayout());

        jPanel11.setBackground(new java.awt.Color(221, 244, 231));
        jPanel11.setPreferredSize(new java.awt.Dimension(10, 774));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 774, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel11, java.awt.BorderLayout.LINE_START);

        jPanel12.setBackground(new java.awt.Color(221, 244, 231));
        jPanel12.setLayout(new java.awt.BorderLayout());

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setPreferredSize(new java.awt.Dimension(763, 425));
        panelRound2.setRoundBottomLeft(50);
        panelRound2.setRoundBottomRight(50);
        panelRound2.setRoundTopLeft(50);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelRound2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));
        panelRound2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 710, 10));

        jLabel6.setFont(new java.awt.Font("Noto Sans Myanmar", 0, 18)); // NOI18N
        jLabel6.setText("Descripción");
        panelRound2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));
        panelRound2.add(jtfNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 240, 40));
        panelRound2.add(jtfPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 240, 40));
        panelRound2.add(jtfStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 240, 40));

        JtaDescripcionProducto.setColumns(20);
        JtaDescripcionProducto.setRows(5);
        jScrollPane2.setViewportView(JtaDescripcionProducto);

        panelRound2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 230, 240, -1));

        btnRegitarProducto.setBackground(new java.awt.Color(38, 102, 127));
        btnRegitarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnRegitarProducto.setText("Guardar producto");
        btnRegitarProducto.setFont(new java.awt.Font("Noto Sans Kannada", 0, 18)); // NOI18N
        btnRegitarProducto.setRoundBottomLeft(30);
        btnRegitarProducto.setRoundBottomRight(30);
        btnRegitarProducto.setRoundTopLeft(30);
        btnRegitarProducto.setRoundTopRight(30);
        btnRegitarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegitarProductoActionPerformed(evt);
            }
        });
        panelRound2.add(btnRegitarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 330, 40));

        jLabel9.setFont(new java.awt.Font("Noto Sans Kannada", 1, 36)); // NOI18N
        jLabel9.setText("Un nuevo Producto");
        panelRound2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 23, -1, -1));

        jLabel10.setFont(new java.awt.Font("Noto Sans Myanmar", 0, 18)); // NOI18N
        jLabel10.setText("Categoria");
        panelRound2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel11.setFont(new java.awt.Font("Noto Sans Myanmar", 0, 18)); // NOI18N
        jLabel11.setText("Nombre");
        panelRound2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel12.setFont(new java.awt.Font("Noto Sans Myanmar", 0, 18)); // NOI18N
        jLabel12.setText("Precio");
        panelRound2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        jLabel13.setFont(new java.awt.Font("Noto Sans Myanmar", 0, 18)); // NOI18N
        jLabel13.setText("Stock");
        panelRound2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        jLabel14.setFont(new java.awt.Font("Noto Sans Myanmar", 0, 18)); // NOI18N
        jLabel14.setText("Estado");
        panelRound2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        jcEstadoProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "Agotado" }));
        panelRound2.add(jcEstadoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 240, 40));

        jcCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcCategoriaActionPerformed(evt);
            }
        });
        panelRound2.add(jcCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 240, 40));

        jPanel12.add(panelRound2, java.awt.BorderLayout.PAGE_START);

        jPanel13.setBackground(new java.awt.Color(221, 244, 231));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jPanel14.setBackground(new java.awt.Color(221, 244, 231));
        jPanel14.setPreferredSize(new java.awt.Dimension(763, 10));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel13.add(jPanel14, java.awt.BorderLayout.PAGE_START);

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setRoundBottomLeft(50);
        panelRound3.setRoundBottomRight(50);
        panelRound3.setRoundTopLeft(50);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Noto Sans Kannada", 1, 36)); // NOI18N
        jLabel2.setText("Buscar Información");
        panelRound3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 23, -1, -1));
        panelRound3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 76, 710, 10));

        jLabel4.setFont(new java.awt.Font("Noto Sans Myanmar", 0, 18)); // NOI18N
        jLabel4.setText("Código");
        panelRound3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Noto Sans Myanmar", 0, 18)); // NOI18N
        jLabel5.setText("Nombre");
        panelRound3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Noto Sans Myanmar", 0, 18)); // NOI18N
        jLabel7.setText("Precio");
        panelRound3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Noto Sans Myanmar", 0, 18)); // NOI18N
        jLabel8.setText("Stock");
        panelRound3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));
        panelRound3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 340, -1));
        panelRound3.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 340, -1));
        panelRound3.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 340, -1));
        panelRound3.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 340, -1));

        jLabel3.setFont(new java.awt.Font("Noto Sans Myanmar", 0, 18)); // NOI18N
        jLabel3.setText("Estado");
        panelRound3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "Agotado" }));
        panelRound3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 340, 40));

        buttonRound2.setBackground(new java.awt.Color(38, 102, 127));
        buttonRound2.setForeground(new java.awt.Color(255, 255, 255));
        buttonRound2.setText("BUSCAR");
        buttonRound2.setRoundBottomLeft(30);
        buttonRound2.setRoundBottomRight(30);
        buttonRound2.setRoundTopLeft(30);
        buttonRound2.setRoundTopRight(30);
        buttonRound2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRound2ActionPerformed(evt);
            }
        });
        panelRound3.add(buttonRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 200, 45));

        buttonRound3.setBackground(new java.awt.Color(38, 102, 127));
        buttonRound3.setForeground(new java.awt.Color(255, 255, 255));
        buttonRound3.setText("EDITAR");
        buttonRound3.setRoundBottomLeft(30);
        buttonRound3.setRoundBottomRight(30);
        buttonRound3.setRoundTopLeft(30);
        buttonRound3.setRoundTopRight(30);
        panelRound3.add(buttonRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 200, 45));

        buttonRound4.setBackground(new java.awt.Color(38, 102, 127));
        buttonRound4.setForeground(new java.awt.Color(255, 255, 255));
        buttonRound4.setText("ELIMINAR");
        buttonRound4.setRoundBottomLeft(30);
        buttonRound4.setRoundBottomRight(30);
        buttonRound4.setRoundTopLeft(30);
        buttonRound4.setRoundTopRight(30);
        buttonRound4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRound4ActionPerformed(evt);
            }
        });
        panelRound3.add(buttonRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 200, 45));

        jPanel13.add(panelRound3, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel6, java.awt.BorderLayout.CENTER);

        add(jPanel5, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegitarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegitarProductoActionPerformed
        // TODO add your handling code here:
        String categoria = (String)jcCategoria.getSelectedItem();
        String nombre = jtfNombreProducto.getText();
        double precio = Double.parseDouble(jtfPrecioProducto.getText());
        int stock = Integer.parseInt(jtfStock.getText());
        String descripcion = JtaDescripcionProducto.getText();
        String estado = (String)jcEstadoProducto.getSelectedItem();
        
        Producto pd = new Producto(nombre, descripcion, precio, stock, estado, categoria);
        emprendedor.getProductos().AdicionarFinal(pd);
        
        JOptionPane.showMessageDialog(null, "Producto agregado correctamente");
        JOptionPane.showMessageDialog(null, "Informacion de producto: " + emprendedor.getProductos().toString());
        
        LimpiarCampos();
        cargarTablaProductos();
        
        
        
        
        
        
    }//GEN-LAST:event_btnRegitarProductoActionPerformed

    private void buttonRound2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRound2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRound2ActionPerformed

    private void buttonRound4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRound4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRound4ActionPerformed

    private void jcCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcCategoriaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jcCategoriaActionPerformed

    public void LimpiarCampos(){
        JtaDescripcionProducto.setText("");
        jtfNombreProducto.setText("");
        jtfPrecioProducto.setText("");
        jtfStock.setText("");
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JtaDescripcionProducto;
    private RoundersComponents.ButtonRound btnRegitarProducto;
    private RoundersComponents.ButtonRound buttonRound2;
    private RoundersComponents.ButtonRound buttonRound3;
    private RoundersComponents.ButtonRound buttonRound4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JComboBox<String> jcCategoria;
    private javax.swing.JComboBox<String> jcEstadoProducto;
    private javax.swing.JTextField jtfNombreProducto;
    private javax.swing.JTextField jtfPrecioProducto;
    private javax.swing.JTextField jtfStock;
    private RoundersComponents.PanelRound panelRound1;
    private RoundersComponents.PanelRound panelRound2;
    private RoundersComponents.PanelRound panelRound3;
    // End of variables declaration//GEN-END:variables
}
