/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Templates;
import javax.swing.JOptionPane;
import models.Usuario;
import models.Main;

/**
 *
 * @author samuelmendoza
 */
public class RegisterClient extends javax.swing.JFrame {

    /**
     * Creates new form RegisterClient
     */
    public RegisterClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelRound1 = new RoundersComponents.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelRound2 = new RoundersComponents.PanelRound();
        panelRound3 = new RoundersComponents.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        txtApellidoCliente = new javax.swing.JTextField();
        txtCorreoCliente = new javax.swing.JTextField();
        buttonRound1 = new RoundersComponents.ButtonRound();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtContraseñaCliente = new javax.swing.JPasswordField();
        btnMostrarPss = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        txtTelefonoCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(18, 65, 112));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(221, 244, 231));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Noto Sans Kannada", 1, 36)); // NOI18N
        jLabel1.setText("PERSONAL");
        jLabel1.setToolTipText("");
        panelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 270, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poo_wep_app/images/ClienteProfileBIG.png"))); // NOI18N
        panelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setRoundBottomLeft(60);
        panelRound2.setRoundBottomRight(60);
        panelRound2.setRoundTopLeft(60);
        panelRound2.setRoundTopRight(60);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound3.setBackground(new java.awt.Color(221, 244, 231));
        panelRound3.setRoundBottomLeft(250);
        panelRound3.setRoundBottomRight(250);
        panelRound3.setRoundTopLeft(250);
        panelRound3.setRoundTopRight(250);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelRound2.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, -150, 250, 240));

        jLabel3.setFont(new java.awt.Font("Noto Nastaliq Urdu", 0, 18)); // NOI18N
        jLabel3.setText("Nombre");
        panelRound2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 90, 30));

        jLabel4.setFont(new java.awt.Font("Noto Nastaliq Urdu", 0, 18)); // NOI18N
        jLabel4.setText("Apellido");
        panelRound2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 90, 30));

        jLabel5.setFont(new java.awt.Font("Noto Nastaliq Urdu", 0, 18)); // NOI18N
        jLabel5.setText("Teléfono ");
        panelRound2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 90, 30));

        jLabel6.setFont(new java.awt.Font("Noto Nastaliq Urdu", 0, 18)); // NOI18N
        jLabel6.setText("Contraeña");
        panelRound2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 110, 30));
        panelRound2.add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 280, 40));
        panelRound2.add(txtApellidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 280, 40));
        panelRound2.add(txtCorreoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 280, 40));

        buttonRound1.setBackground(new java.awt.Color(38, 102, 127));
        buttonRound1.setForeground(new java.awt.Color(255, 255, 255));
        buttonRound1.setText("REGISTRAR");
        buttonRound1.setRoundBottomLeft(30);
        buttonRound1.setRoundBottomRight(30);
        buttonRound1.setRoundTopLeft(30);
        buttonRound1.setRoundTopRight(30);
        buttonRound1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRound1ActionPerformed(evt);
            }
        });
        panelRound2.add(buttonRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 280, 50));

        jLabel8.setFont(new java.awt.Font("Skia", 0, 24)); // NOI18N
        jLabel8.setText("CLIENTE");
        jLabel8.setToolTipText("");
        panelRound2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 270, 40));

        jLabel9.setFont(new java.awt.Font("Skia", 0, 24)); // NOI18N
        jLabel9.setText("PERFIL DE");
        jLabel9.setToolTipText("");
        panelRound2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 270, 50));
        panelRound2.add(txtContraseñaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 280, 40));

        btnMostrarPss.setText("Mostrar ");
        btnMostrarPss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarPssActionPerformed(evt);
            }
        });
        panelRound2.add(btnMostrarPss, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        jLabel10.setFont(new java.awt.Font("Noto Nastaliq Urdu", 0, 18)); // NOI18N
        jLabel10.setText("Correo");
        panelRound2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 90, 30));
        panelRound2.add(txtTelefonoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 280, 40));

        panelRound1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 740, 490));

        jLabel7.setFont(new java.awt.Font("Noto Sans Kannada", 1, 36)); // NOI18N
        jLabel7.setText("INFORMACIÓN");
        jLabel7.setToolTipText("");
        panelRound1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 270, 60));

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 190, 790, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRound1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRound1ActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombreCliente.getText();
        String Apellido = txtApellidoCliente.getText();
        String tel = txtTelefonoCliente.getText();
        String Correo = txtCorreoCliente.getText();
        String Contraseña = txtContraseñaCliente.getText();
        
        Usuario u = new Usuario(nombre, Apellido, tel, Correo, Contraseña, "Cliente");
        models.Main.GetListaUsuarios().AdicionarFinal(u);
//        JOptionPane.showMessageDialog(null, "Cliente Registrado correctamente" + 
//                                            "\nInformacion: " + 
//                                            c.toString());

        RegistroCompletado frameB = new RegistroCompletado(nombre);
        frameB.setVisible(true);
        
        
        
        
        
        
        
    }//GEN-LAST:event_buttonRound1ActionPerformed

    private void btnMostrarPssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarPssActionPerformed
        // TODO add your handling code here:
        if (btnMostrarPss.isSelected()) {
        // Mostrar contraseña en texto plano
            txtContraseñaCliente.setEchoChar((char) 0);
        } else {
            // Ocultar contraseña con *
            txtContraseñaCliente.setEchoChar('*');
        }
            
    }//GEN-LAST:event_btnMostrarPssActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox btnMostrarPss;
    private RoundersComponents.ButtonRound buttonRound1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private RoundersComponents.PanelRound panelRound1;
    private RoundersComponents.PanelRound panelRound2;
    private RoundersComponents.PanelRound panelRound3;
    private javax.swing.JTextField txtApellidoCliente;
    private javax.swing.JPasswordField txtContraseñaCliente;
    private javax.swing.JTextField txtCorreoCliente;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtTelefonoCliente;
    // End of variables declaration//GEN-END:variables
}
