/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Templates;
import models.Main;


/**
 *
 * @author samuelmendoza
 */
public class RegistroCompletado extends javax.swing.JFrame {
    
    
    
    

    public RegistroCompletado(String nombre) {
        initComponents();
        
        LabelNombreCliente.setText(nombre + ",");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new RoundersComponents.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        LabelNombreCliente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonRound1 = new RoundersComponents.ButtonRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelRound1.setBackground(new java.awt.Color(221, 244, 231));
        panelRound1.setPreferredSize(new java.awt.Dimension(520, 320));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poo_wep_app/images/Check.png"))); // NOI18N
        panelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        LabelNombreCliente.setFont(new java.awt.Font("Noto Sans Myanmar", 1, 48)); // NOI18N
        LabelNombreCliente.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                LabelNombreClienteComponentAdded(evt);
            }
        });
        panelRound1.add(LabelNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 260, 80));

        jLabel2.setFont(new java.awt.Font("Noto Sans Myanmar", 0, 18)); // NOI18N
        jLabel2.setText("Te haz registrado correctamente");
        panelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        buttonRound1.setText("INICIAR SESIÓN");
        buttonRound1.setRoundBottomLeft(20);
        buttonRound1.setRoundBottomRight(20);
        buttonRound1.setRoundTopLeft(20);
        buttonRound1.setRoundTopRight(20);
        buttonRound1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRound1ActionPerformed(evt);
            }
        });
        panelRound1.add(buttonRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 150, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelNombreClienteComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_LabelNombreClienteComponentAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_LabelNombreClienteComponentAdded

    private void buttonRound1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRound1ActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonRound1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelNombreCliente;
    private RoundersComponents.ButtonRound buttonRound1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private RoundersComponents.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables
}
